"""add candidatures table

Revision ID: 313c67e7b441
Revises: e9299d9e312d
Create Date: 2026-03-25 12:13:00.294368
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '313c67e7b441'
down_revision: Union[str, None] = 'e9299d9e312d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.Enum('SOUMISE', 'EN_COURS_EXAMEN', 'ACCEPTEE', 'REFUSEE', name='statutcandidature'), nullable=False),
    sa.Column('cv_nom_fichier', sa.String(), nullable=False),
    sa.Column('cv_url_stockage', sa.String(), nullable=False),
    sa.Column('candidat_id', sa.UUID(), nullable=False),
    sa.Column('offre_id', sa.UUID(), nullable=False),
    sa.Column('date_postulation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidat_id', 'offre_id', name='uq_candidature_candidat_offre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatures')
    # ### end Alembic commands ###
