"""add offres table

Revision ID: 9a417b8e834a
Revises: b67834e3007c
Create Date: 2026-03-25 11:08:28.926459
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9a417b8e834a'
down_revision: Union[str, None] = 'b67834e3007c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('domaine', sa.String(), nullable=False),
    sa.Column('competences_requises', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('annees_experience_min', sa.Integer(), nullable=True),
    sa.Column('date_debut_souhaitee', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'PUBLIEE', 'FERMEE', name='statutoffre'), nullable=False),
    sa.Column('recruteur_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recruteur_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offres')
    # ### end Alembic commands ###
