"""add offres table

Revision ID: e9299d9e312d
Revises: 9a417b8e834a
Create Date: 2026-03-25 11:57:51.243883
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e9299d9e312d'
down_revision: Union[str, None] = '9a417b8e834a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
